title : Baseball Hack Day, March 9, 2019 - Friendly one-day multi-city coding competition for baseball fans
description : Friendly one-day multi-city coding competition for baseball fans - Baseball Hack Day
keyword : baseball, hackday, hackathon, hack, hacking, hackfest, codefest, mlb, major league baseball
url : http://www.baseballhackday.com
baseurl : /
email : daigo@baseballhackday.com
twitter : baseballhackday
socialimage: http://www.baseballhackday.com/images/bbhd-2018.png
markdown: kramdown
exclude :
  - node_modules
