title : Baseball Hack Day, March 11, 2023 - Friendly one-day multi-city coding competition for baseball fans
description : Friendly one-day multi-city coding competition for baseball fans - Baseball Hack Day Sat. March 11, 2023
keyword : baseball, hackday, hackathon, hack, hacking, hackfest, codefest, mlb, major league baseball
url : http://www.baseballhackday.com
baseurl : /
email : daigo@baseballhackday.com
twitter : baseballhackday
socialimage: http://www.baseballhackday.com/images/bbhd-2023.png
markdown: kramdown
exclude : [node_modules, bower_components, vendor]
